### ISSUE TITLE
Account creation issue

### ISSUE THREAD

**Issue by stevesbrain** [mdouchement/standardfile#27]
Hi there!

First up: love the project. Backend makes a super fast alternative to the official run (which runs very slowly on my own services when compared to this one). However, one small issue - on account creation, it immediately goes to an "expired session" forcing me to log out, and then back in again. Not a big deal by any means, but still something worth looking at in future :)

**Comment by mdouchement** [comment]
Thanks for reporting the issue.
At a first thought if [user.PasswordUpdatedAt](https://github.com/mdouchement/standardfile/blob/master/internal/server/auth_handlers.go#L87) and [claims["iat"]](https://github.com/mdouchement/standardfile/blob/master/internal/server/auth_handlers.go#L284) timestamps are generated within the same second the authentication token will be [revoked](https://github.com/mdouchement/standardfile/blob/master/internal/server/middlewares/current_user.go#L55).
I will investigate furthermore next week.
