### ISSUE TITLE
invalid login credentials (on registration)

### ISSUE THREAD

**Issue by cyberb** [mdouchement/standardfile#64]
I am trying to test notes web v3.8.18 against latest sf and I am getting invalid login credentials as soon as I register (I do not even have a chance to enter login/password).
Request:

```
{
 "password":"***",
 "email":"***",
 "ephemeral":false,
 "identifier":"***",
 "pw_nonce":"***",
 "version":"004",
 "origination":
 "registration",
 "created":"1631372134116",
 "api":"20200115"}
```

Server says:
```
[401] POST /api/v1/users (326) 7.372964ms
```

**Comment by mdouchement** [comment]
Since few months, the Standard Notes team is changing the API and the response format while moving to there new infrastructure.
I'm currently working on a branch that tries to implement these daily changes.

**Comment by cyberb** [comment]
Great, what is the last compatible version I should use for now?

**Comment by mdouchement** [comment]
`api` version `20190520` should work

**Comment by mdouchement** [comment]
Latest release `0.6.8` works.
You have to enable registration in configuration file: `no_registration: false`.
This option is used to avoid unwanted users using your server.

**Comment by cyberb** [comment]
I had this option already disabled, let me test 0.6.8

**Comment by cyberb** [comment]
same error on 0.6.8 + 3.8.21
`no_registration: false`
`notes.server[1625]: [401] POST /api/v1/users (322) 124.23Âµs`

**Comment by mdouchement** [comment]
It works on macOS with StandardNotes Desktop 3.8.21 and server on 0.6.8. It also works with https://app.standardnotes.org/

```
   ____    __
  / __/___/ /  ___
 / _// __/ _ \/ _ \
/___/\__/_//_/\___/ v4.5.0
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
                                    O\
⇨ http server started on 127.0.0.1:5000
[200] POST /v1/users (304) 117.132324ms
[200] POST /v1/items (67) 1.013378ms
[200] POST /v1/items (3521) 36.052648ms
```

I only get this error when registration is disabled:
```
   ____    __
  / __/___/ /  ___
 / _// __/ _ \/ _ \
/___/\__/_//_/\___/ v4.5.0
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
                                    O\
⇨ http server started on 127.0.0.1:5000
[401] POST /v1/users (304) 141.786µs
```
_which should return a `404 Not Found` and not a `401 Unauthorized`. I'll fix that later._

Could this issue is due to serving through a socket domain? As Echo is not made for that.

**Comment by cyberb** [comment]
oh, I have nginx in front of sf and it seems I am not taking /api prefix out:
```
[401] POST /api/v1/users (326) 7.372964ms
```
but in that case why is it not 404 already, let me fix that

**Comment by cyberb** [comment]
removing the /api prefix fixed it!
