### ISSUE TITLE
Add docker image scheduled build for latest tags

### ISSUE THREAD

**Issue by mdouchement** [mdouchement/standardfile#66]
https://github.com/mdouchement/standardfile/blob/master/.github/workflows/docker.yml#L4

Maybe using `https://api.github.com/repos/mdouchement/standardfile/releases/latest`

**Comment by Robert-Ernst** [comment]
Any updates here?

**Comment by mdouchement** [comment]
```
error: pathspec 'v0.6.8' did not match any file(s) known to git
Error: Process completed with exit code 1.
```

Forcing `fetch-depth: 0` on [actions/checkout@v2](https://github.com/actions/checkout) should resolve the bug.
