### ISSUE TITLE
Unable to use with latest client sources

### ISSUE THREAD

**Issue by shagr4th** [mdouchement/standardfile#77]
Hello !

Latest standardnotes client can't connect anymore to this wonderful server
Probably because of this: https://github.com/standardnotes/snjs/commit/1bc19b79decf83a563d1cf095ee2e56f738152d1

New routes (/v2/***) to implement ?

**Comment by Platun0v** [comment]
The same. Have problems with authentication in recent web client

**Comment by valantur** [comment]
Are you running a pre-release version of the client? I'm on 3.20.0 and everything works fine.

**Comment by Platun0v** [comment]
Im using web client, where the version is 3.20.2

**Comment by mdouchement** [comment]
Should be resolved in the latest release https://github.com/mdouchement/standardfile/releases/tag/v0.7.0
