### ISSUE TITLE
Unable to login with latest server and Android app

### ISSUE THREAD

**Issue by squalus** [mdouchement/standardfile#82]
I'm using standardfile v0.7.1 and Android Standard Notes 3.26.14 (latest version on f-droid). I expected [#77](https://github.com/mdouchement/standardfile/pull/78) to fix this, but I get a 401 error from the new `v2/login-params` API.

```
Jul 10 12:00:48 xxxxx standardfile[828]: [401] POST /v2/login-params (149) 1.110931ms
```

**Comment by shagr4th** [comment]
Hi. FWIW, the same build works fine on my end :

`[200] POST /v2/login-params (153) 3.737602ms
[200] POST /v2/login (226) 257.497839ms
[200] POST /v1/items (41) 21.199569ms`

**Comment by mdouchement** [comment]
I've successfully login with Android client `3.23.8 (3002010)`

**Comment by squalus** [comment]
Same issue for me in the Desktop client 3.23.69. Verified that an older client works with the same credentials (3.11.1)

**Comment by squalus** [comment]
It works fine with the new client if I make a fresh database, but not if I use my existing database. Maybe some kind of a migration issue?

**Comment by squalus** [comment]
OK, I think this was just a build system mixup for me. Once I got that sorted out, 0.7.1 works properly with Desktop 3.23.69 and Android 3.26.14. Sorry!
