### ISSUE TITLE
secret key not found

### ISSUE THREAD

**Issue by mtoniott** [mdouchement/standardfile#84]
Hey,

I'm trying to install this on my local machine, but it refuses to start.

I first initialized the db with:
standardfile init -c /etc/standardfile.yaml

which worked. Then I tried to start the server with:

standardfile server -c /etc/standarfile.yaml.

Which gave me the following output:

Error: secret_key not found
Usage:
  standardfile server [flags]

Flags:
  -c, --config string   Configuration file
  -h, --help            help for server

2022/07/26 13:28:14 secret_key not found
main.glob..func3
	/home/runner/work/standardfile/standardfile/cmd/standardfile/main.go:126
github.com/spf13/cobra.(*Command).execute
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872
github.com/spf13/cobra.(*Command).ExecuteC
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990
github.com/spf13/cobra.(*Command).Execute
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main
	/home/runner/work/standardfile/standardfile/cmd/standardfile/main.go:51
runtime.main
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/proc.go:250
runtime.goexit
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/asm_amd64.s:1571

What did I miss ? Sorry if it is a dumb question.

**Comment by mdouchement** [comment]
Hello,

This error is raised when `secret_key` is empty in the configuration file. This field is not required by the `init` command.
